namespace MSUIClient.Formats;

// ─────────────────────────────────────────────────────────────────────────────
// Vanilla tier-set data (T0, T0.5, T1, T2, T3), ported verbatim from
// MangosSuperUI wwwroot/js/character-viewer/tier-sets.js (itself generated by
// dump_tiers.sql against item_template with (entry, MAX(patch)) dedup).
// InventoryType is item_template.inventory_type: 1=head 3=shoulder 5=chest
// 6=waist 7=legs 8=feet 9=wrist 10=hands 20=robe. Pieces read top-down on a
// paper doll. THIS FILE IS GENERATED - regenerate from the JS, don't hand-edit.
// ─────────────────────────────────────────────────────────────────────────────
public static class CreatorTierSets
{
    public readonly record struct Piece(string Name, uint ItemId, uint DisplayId, int InventoryType);

    public static readonly string[] Classes;
    public static readonly string[] Tiers = { "T0", "T0.5", "T1", "T2", "T3" };
    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, Piece[]>> Sets;

    static CreatorTierSets()
    {
        var sets = new Dictionary<string, IReadOnlyDictionary<string, Piece[]>>();
        sets["Druid"] = new Dictionary<string, Piece[]>
        {
            ["T0"] = new Piece[]
            {
                new("Wildheart Cowl", 16720, 31228, 1),
                new("Wildheart Spaulders", 16718, 30412, 3),
                new("Wildheart Vest", 16706, 29974, 5),
                new("Wildheart Belt", 16716, 29976, 6),
                new("Wildheart Kilt", 16719, 29975, 7),
                new("Wildheart Boots", 16715, 29981, 8),
                new("Wildheart Bracers", 16714, 29977, 9),
                new("Wildheart Gloves", 16717, 29979, 10),
            },
            ["T0.5"] = new Piece[]
            {
                new("Feralheart Cowl", 22109, 34639, 1),
                new("Feralheart Spaulders", 22112, 34643, 3),
                new("Feralheart Vest", 22113, 34644, 5),
                new("Feralheart Belt", 22106, 34637, 6),
                new("Feralheart Kilt", 22111, 34642, 7),
                new("Feralheart Boots", 22107, 34638, 8),
                new("Feralheart Bracers", 22108, 34641, 9),
                new("Feralheart Gloves", 22110, 34640, 10),
            },
            ["T1"] = new Piece[]
            {
                new("Cenarion Helm", 16834, 32790, 1),
                new("Cenarion Spaulders", 16836, 32016, 3),
                new("Cenarion Vestments", 16833, 31797, 20),
                new("Cenarion Belt", 16828, 31722, 6),
                new("Cenarion Leggings", 16835, 31729, 7),
                new("Cenarion Boots", 16829, 31724, 8),
                new("Cenarion Bracers", 16830, 31725, 9),
                new("Cenarion Gloves", 16831, 31726, 10),
            },
            ["T2"] = new Piece[]
            {
                new("Stormrage Cover", 16900, 33655, 1),
                new("Stormrage Pauldrons", 16902, 30546, 3),
                new("Stormrage Chestguard", 16897, 30536, 5),
                new("Stormrage Belt", 16903, 30541, 6),
                new("Stormrage Legguards", 16901, 30540, 7),
                new("Stormrage Boots", 16898, 30542, 8),
                new("Stormrage Bracers", 16904, 30548, 9),
                new("Stormrage Handguards", 16899, 34016, 10),
            },
            ["T3"] = new Piece[]
            {
                new("Dreamwalker Headpiece", 22490, 35162, 1),
                new("Dreamwalker Spaulders", 22491, 35160, 3),
                new("Dreamwalker Tunic", 22488, 35159, 5),
                new("Dreamwalker Girdle", 22494, 35164, 6),
                new("Dreamwalker Legguards", 22489, 35161, 7),
                new("Dreamwalker Boots", 22492, 35173, 8),
                new("Dreamwalker Wristguards", 22495, 35158, 9),
                new("Dreamwalker Handguards", 22493, 35167, 10),
            },
        };
        sets["Hunter"] = new Dictionary<string, Piece[]>
        {
            ["T0"] = new Piece[]
            {
                new("Beaststalker's Cap", 16677, 31410, 1),
                new("Beaststalker's Mantle", 16679, 31409, 3),
                new("Beaststalker's Tunic", 16674, 31402, 5),
                new("Beaststalker's Belt", 16680, 31404, 6),
                new("Beaststalker's Pants", 16678, 31403, 7),
                new("Beaststalker's Boots", 16675, 31408, 8),
                new("Beaststalker's Bindings", 16681, 31405, 9),
                new("Beaststalker's Gloves", 16676, 31406, 10),
            },
            ["T0.5"] = new Piece[]
            {
                new("Beastmaster's Cap", 22013, 34649, 1),
                new("Beastmaster's Mantle", 22016, 34651, 3),
                new("Beastmaster's Tunic", 22060, 34645, 5),
                new("Beastmaster's Belt", 22010, 34646, 6),
                new("Beastmaster's Pants", 22017, 34652, 7),
                new("Beastmaster's Boots", 22061, 34648, 8),
                new("Beastmaster's Bindings", 22011, 34647, 9),
                new("Beastmaster's Gloves", 22015, 34650, 10),
            },
            ["T1"] = new Piece[]
            {
                new("Giantstalker's Helmet", 16846, 32028, 1),
                new("Giantstalker's Epaulets", 16848, 32030, 3),
                new("Giantstalker's Breastplate", 16845, 32022, 5),
                new("Giantstalker's Belt", 16851, 32019, 6),
                new("Giantstalker's Leggings", 16847, 32029, 7),
                new("Giantstalker's Boots", 16849, 32040, 8),
                new("Giantstalker's Bracers", 16850, 32021, 9),
                new("Giantstalker's Gloves", 16852, 32024, 10),
            },
            ["T2"] = new Piece[]
            {
                new("Dragonstalker's Helm", 16939, 34367, 1),
                new("Dragonstalker's Spaulders", 16937, 34091, 3),
                new("Dragonstalker's Breastplate", 16942, 33667, 5),
                new("Dragonstalker's Belt", 16936, 33665, 6),
                new("Dragonstalker's Legguards", 16938, 33672, 7),
                new("Dragonstalker's Greaves", 16941, 34269, 8),
                new("Dragonstalker's Bracers", 16935, 33666, 9),
                new("Dragonstalker's Gauntlets", 16940, 33668, 10),
            },
            ["T3"] = new Piece[]
            {
                new("Cryptstalker Headpiece", 22438, 35601, 1),
                new("Cryptstalker Spaulders", 22439, 35611, 3),
                new("Cryptstalker Tunic", 22436, 35415, 5),
                new("Cryptstalker Girdle", 22442, 35410, 6),
                new("Cryptstalker Legguards", 22437, 35413, 7),
                new("Cryptstalker Boots", 22440, 35409, 8),
                new("Cryptstalker Wristguards", 22443, 35416, 9),
                new("Cryptstalker Handguards", 22441, 35411, 10),
            },
        };
        sets["Mage"] = new Dictionary<string, Piece[]>
        {
            ["T0"] = new Piece[]
            {
                new("Magister's Crown", 16686, 31087, 1),
                new("Magister's Mantle", 16689, 30211, 3),
                new("Magister's Robes", 16688, 29591, 20),
                new("Magister's Belt", 16685, 29596, 6),
                new("Magister's Leggings", 16687, 29273, 7),
                new("Magister's Boots", 16682, 29594, 8),
                new("Magister's Bindings", 16683, 29597, 9),
                new("Magister's Gloves", 16684, 29593, 10),
            },
            ["T0.5"] = new Piece[]
            {
                new("Sorcerer's Crown", 22065, 34602, 1),
                new("Sorcerer's Mantle", 22068, 34597, 3),
                new("Sorcerer's Robes", 22069, 34596, 20),
                new("Sorcerer's Belt", 22062, 34599, 6),
                new("Sorcerer's Leggings", 22067, 34598, 7),
                new("Sorcerer's Boots", 22064, 34782, 8),
                new("Sorcerer's Bindings", 22063, 34601, 9),
                new("Sorcerer's Gloves", 22066, 34600, 10),
            },
            ["T1"] = new Piece[]
            {
                new("Arcanist Crown", 16795, 31517, 1),
                new("Arcanist Mantle", 16797, 30586, 3),
                new("Arcanist Robes", 16798, 30581, 20),
                new("Arcanist Belt", 16802, 30583, 6),
                new("Arcanist Leggings", 16796, 30582, 7),
                new("Arcanist Boots", 16800, 30587, 8),
                new("Arcanist Bindings", 16799, 30584, 9),
                new("Arcanist Gloves", 16801, 30585, 10),
            },
            ["T2"] = new Piece[]
            {
                new("Netherwind Crown", 16914, 34218, 1),
                new("Netherwind Mantle", 16917, 34254, 3),
                new("Netherwind Robes", 16916, 34038, 20),
                new("Netherwind Belt", 16818, 34046, 6),
                new("Netherwind Pants", 16915, 34039, 7),
                new("Netherwind Boots", 16912, 34044, 8),
                new("Netherwind Bindings", 16918, 34045, 9),
                new("Netherwind Gloves", 16913, 34041, 10),
            },
            ["T3"] = new Piece[]
            {
                new("Frostfire Circlet", 22498, 36440, 1),
                new("Frostfire Shoulderpads", 22499, 35326, 3),
                new("Frostfire Robe", 22496, 35523, 20),
                new("Frostfire Belt", 22502, 35519, 6),
                new("Frostfire Leggings", 22497, 35522, 7),
                new("Frostfire Sandals", 22500, 35525, 8),
                new("Frostfire Bindings", 22503, 35677, 9),
                new("Frostfire Gloves", 22501, 35521, 10),
                new("Frostfire Ring", 23062, 35472, 11),
            },
        };
        sets["Paladin"] = new Dictionary<string, Piece[]>
        {
            ["T0"] = new Piece[]
            {
                new("Lightforge Helm", 16727, 31207, 1),
                new("Lightforge Spaulders", 16729, 29971, 3),
                new("Lightforge Breastplate", 16726, 29969, 5),
                new("Lightforge Belt", 16723, 29966, 6),
                new("Lightforge Legplates", 16728, 29972, 7),
                new("Lightforge Boots", 16725, 29967, 8),
                new("Lightforge Bracers", 16722, 29968, 9),
                new("Lightforge Gauntlets", 16724, 29970, 10),
            },
            ["T0.5"] = new Piece[]
            {
                new("Soulforge Helm", 22091, 34524, 1),
                new("Soulforge Spaulders", 22093, 34526, 3),
                new("Soulforge Breastplate", 22089, 34519, 5),
                new("Soulforge Belt", 22086, 34520, 6),
                new("Soulforge Legplates", 22092, 34525, 7),
                new("Soulforge Boots", 22087, 34521, 8),
                new("Soulforge Bracers", 22088, 34522, 9),
                new("Soulforge Gauntlets", 22090, 34523, 10),
            },
            ["T1"] = new Piece[]
            {
                new("Lawbringer Helm", 16854, 31506, 1),
                new("Lawbringer Spaulders", 16856, 31510, 3),
                new("Lawbringer Chestguard", 16853, 31505, 5),
                new("Lawbringer Belt", 16858, 31353, 6),
                new("Lawbringer Legplates", 16855, 31352, 7),
                new("Lawbringer Boots", 16859, 31354, 8),
                new("Lawbringer Bracers", 16857, 31509, 9),
                new("Lawbringer Gauntlets", 16860, 31507, 10),
            },
            ["T2"] = new Piece[]
            {
                new("Judgement Crown", 16955, 34216, 1),
                new("Judgement Spaulders", 16953, 34258, 3),
                new("Judgement Breastplate", 16958, 33635, 5),
                new("Judgement Belt", 16952, 33633, 6),
                new("Judgement Legplates", 16954, 33637, 7),
                new("Judgement Sabatons", 16957, 33639, 8),
                new("Judgement Bindings", 16951, 33634, 9),
                new("Judgement Gauntlets", 16956, 33636, 10),
            },
            ["T3"] = new Piece[]
            {
                new("Redemption Headpiece", 22428, 36972, 1),
                new("Redemption Spaulders", 22429, 35617, 3),
                new("Redemption Tunic", 22425, 35618, 5),
                new("Redemption Girdle", 22431, 35614, 6),
                new("Redemption Legguards", 22427, 35616, 7),
                new("Redemption Boots", 22430, 35613, 8),
                new("Redemption Wristguards", 22424, 35619, 9),
                new("Redemption Handguards", 22426, 35615, 10),
            },
        };
        sets["Priest"] = new Dictionary<string, Piece[]>
        {
            ["T0"] = new Piece[]
            {
                new("Devout Crown", 16693, 31104, 1),
                new("Devout Mantle", 16695, 31103, 3),
                new("Devout Robe", 16690, 30422, 20),
                new("Devout Belt", 16696, 30425, 6),
                new("Devout Skirt", 16694, 30424, 7),
                new("Devout Sandals", 16691, 30430, 8),
                new("Devout Bracers", 16697, 30426, 9),
                new("Devout Gloves", 16692, 30427, 10),
            },
            ["T0.5"] = new Piece[]
            {
                new("Virtuous Crown", 22080, 34630, 1),
                new("Virtuous Mantle", 22082, 34632, 3),
                new("Virtuous Robe", 22083, 34633, 20),
                new("Virtuous Belt", 22078, 34628, 6),
                new("Virtuous Skirt", 22085, 34635, 7),
                new("Virtuous Sandals", 22084, 34634, 8),
                new("Virtuous Bracers", 22079, 34629, 9),
                new("Virtuous Gloves", 22081, 34631, 10),
            },
            ["T1"] = new Piece[]
            {
                new("Circlet of Prophecy", 16813, 31371, 1),
                new("Mantle of Prophecy", 16816, 30623, 3),
                new("Robes of Prophecy", 16815, 31490, 20),
                new("Girdle of Prophecy", 16817, 30621, 6),
                new("Pants of Prophecy", 16814, 28198, 7),
                new("Boots of Prophecy", 16811, 31718, 8),
                new("Vambraces of Prophecy", 16819, 30617, 9),
                new("Gloves of Prophecy", 16812, 30620, 10),
            },
            ["T2"] = new Piece[]
            {
                new("Halo of Transcendence", 16921, 34233, 1),
                new("Pauldrons of Transcendence", 16924, 34048, 3),
                new("Robes of Transcendence", 16923, 34047, 20),
                new("Belt of Transcendence", 16925, 34053, 6),
                new("Leggings of Transcendence", 16922, 34049, 7),
                new("Boots of Transcendence", 16919, 34055, 8),
                new("Bindings of Transcendence", 16926, 34052, 9),
                new("Handguards of Transcendence", 16920, 34051, 10),
            },
            ["T3"] = new Piece[]
            {
                new("Circlet of Faith", 22514, 35155, 1),
                new("Shoulderpads of Faith", 22515, 35149, 3),
                new("Robe of Faith", 22512, 36354, 20),
                new("Belt of Faith", 22518, 35143, 6),
                new("Leggings of Faith", 22513, 35154, 7),
                new("Sandals of Faith", 22516, 35148, 8),
                new("Bindings of Faith", 22519, 35144, 9),
                new("Gloves of Faith", 22517, 35145, 10),
                new("Ring of Faith", 23061, 35472, 11),
            },
        };
        sets["Rogue"] = new Dictionary<string, Piece[]>
        {
            ["T0"] = new Piece[]
            {
                new("Shadowcraft Cap", 16707, 28180, 1),
                new("Shadowcraft Spaulders", 16708, 28179, 3),
                new("Shadowcraft Tunic", 16721, 28160, 5),
                new("Shadowcraft Belt", 16713, 28177, 6),
                new("Shadowcraft Pants", 16709, 28161, 7),
                new("Shadowcraft Boots", 16711, 28162, 8),
                new("Shadowcraft Bracers", 16710, 24190, 9),
                new("Shadowcraft Gloves", 16712, 28166, 10),
            },
            ["T0.5"] = new Piece[]
            {
                new("Darkmantle Cap", 22005, 34700, 1),
                new("Darkmantle Spaulders", 22008, 34688, 3),
                new("Darkmantle Tunic", 22009, 34689, 5),
                new("Darkmantle Belt", 22002, 34699, 6),
                new("Darkmantle Pants", 22007, 34687, 7),
                new("Darkmantle Boots", 22003, 34684, 8),
                new("Darkmantle Bracers", 22004, 34685, 9),
                new("Darkmantle Gloves", 22006, 34686, 10),
            },
            ["T1"] = new Piece[]
            {
                new("Nightslayer Cover", 16821, 31514, 1),
                new("Nightslayer Shoulder Pads", 16823, 31504, 3),
                new("Nightslayer Chestpiece", 16820, 31105, 5),
                new("Nightslayer Belt", 16827, 31339, 6),
                new("Nightslayer Pants", 16822, 31340, 7),
                new("Nightslayer Boots", 16824, 31109, 8),
                new("Nightslayer Bracelets", 16825, 31106, 9),
                new("Nightslayer Gloves", 16826, 31503, 10),
            },
            ["T2"] = new Piece[]
            {
                new("Bloodfang Hood", 16908, 33743, 1),
                new("Bloodfang Spaulders", 16832, 33653, 3),
                new("Bloodfang Chestpiece", 16905, 33650, 5),
                new("Bloodfang Belt", 16910, 31110, 6),
                new("Bloodfang Pants", 16909, 31115, 7),
                new("Bloodfang Boots", 16906, 31111, 8),
                new("Bloodfang Bracers", 16911, 31127, 9),
                new("Bloodfang Gloves", 16907, 33651, 10),
            },
            ["T3"] = new Piece[]
            {
                new("Bonescythe Helmet", 22478, 35132, 1),
                new("Bonescythe Pauldrons", 22479, 35064, 3),
                new("Bonescythe Breastplate", 22476, 35054, 5),
                new("Bonescythe Waistguard", 22482, 36349, 6),
                new("Bonescythe Legplates", 22477, 35065, 7),
                new("Bonescythe Sabatons", 22480, 36351, 8),
                new("Bonescythe Bracers", 22483, 35053, 9),
                new("Bonescythe Gauntlets", 22481, 35055, 10),
                new("Bonescythe Ring", 23060, 35472, 11),
            },
        };
        sets["Shaman"] = new Dictionary<string, Piece[]>
        {
            ["T0"] = new Piece[]
            {
                new("Coif of Elements", 16667, 31117, 1),
                new("Pauldrons of Elements", 16669, 30925, 3),
                new("Vest of Elements", 16666, 31416, 5),
                new("Cord of Elements", 16673, 31413, 6),
                new("Kilt of Elements", 16668, 31415, 7),
                new("Boots of Elements", 16670, 31412, 8),
                new("Bindings of Elements", 16671, 31411, 9),
                new("Gauntlets of Elements", 16672, 31414, 10),
            },
            ["T0.5"] = new Piece[]
            {
                new("Coif of The Five Thunders", 22097, 34693, 1),
                new("Pauldrons of The Five Thunders", 22101, 34697, 3),
                new("Vest of The Five Thunders", 22102, 34698, 5),
                new("Cord of The Five Thunders", 22098, 34694, 6),
                new("Kilt of The Five Thunders", 22100, 34696, 7),
                new("Boots of The Five Thunders", 22096, 34692, 8),
                new("Bindings of The Five Thunders", 22095, 34691, 9),
                new("Gauntlets of The Five Thunders", 22099, 34695, 10),
            },
            ["T1"] = new Piece[]
            {
                new("Earthfury Helmet", 16842, 31835, 1),
                new("Earthfury Epaulets", 16844, 31833, 3),
                new("Earthfury Vestments", 16841, 31832, 20),
                new("Earthfury Belt", 16838, 31829, 6),
                new("Earthfury Legguards", 16843, 31836, 7),
                new("Earthfury Boots", 16837, 31830, 8),
                new("Earthfury Bracers", 16840, 31831, 9),
                new("Earthfury Gauntlets", 16839, 31834, 10),
            },
            ["T2"] = new Piece[]
            {
                new("Helmet of Ten Storms", 16947, 34217, 1),
                new("Epaulets of Ten Storms", 16945, 34255, 3),
                new("Breastplate of Ten Storms", 16950, 34081, 5),
                new("Belt of Ten Storms", 16944, 34078, 6),
                new("Legplates of Ten Storms", 16946, 34084, 7),
                new("Greaves of Ten Storms", 16949, 34083, 8),
                new("Bracers of Ten Storms", 16943, 34079, 9),
                new("Gauntlets of Ten Storms", 16948, 34082, 10),
            },
            ["T3"] = new Piece[]
            {
                new("Earthshatter Headpiece", 22466, 37056, 1),
                new("Earthshatter Spaulders", 22467, 35751, 3),
                new("Earthshatter Tunic", 22464, 35752, 5),
                new("Earthshatter Girdle", 22470, 35747, 6),
                new("Earthshatter Legguards", 22465, 35754, 7),
                new("Earthshatter Boots", 22468, 35746, 8),
                new("Earthshatter Wristguards", 22471, 35753, 9),
                new("Earthshatter Handguards", 22469, 35748, 10),
            },
        };
        sets["Warlock"] = new Dictionary<string, Piece[]>
        {
            ["T0"] = new Piece[]
            {
                new("Dreadmist Mask", 16698, 31263, 1),
                new("Dreadmist Mantle", 16701, 29798, 3),
                new("Dreadmist Robe", 16700, 29792, 20),
                new("Dreadmist Belt", 16702, 29793, 6),
                new("Dreadmist Leggings", 16699, 29797, 7),
                new("Dreadmist Sandals", 16704, 29799, 8),
                new("Dreadmist Bracers", 16703, 29795, 9),
                new("Dreadmist Wraps", 16705, 29800, 10),
            },
            ["T0.5"] = new Piece[]
            {
                new("Deathmist Mask", 22074, 34624, 1),
                new("Deathmist Mantle", 22073, 34623, 3),
                new("Deathmist Robe", 22075, 34625, 20),
                new("Deathmist Belt", 22070, 34620, 6),
                new("Deathmist Leggings", 22072, 34622, 7),
                new("Deathmist Sandals", 22076, 34626, 8),
                new("Deathmist Bracers", 22071, 34621, 9),
                new("Deathmist Wraps", 22077, 34627, 10),
            },
            ["T1"] = new Piece[]
            {
                new("Felheart Horns", 16808, 31987, 1),
                new("Felheart Shoulder Pads", 16807, 31974, 3),
                new("Felheart Robes", 16809, 31973, 20),
                new("Felheart Belt", 16806, 31969, 6),
                new("Felheart Pants", 16810, 31972, 7),
                new("Felheart Slippers", 16803, 31975, 8),
                new("Felheart Bracers", 16804, 31970, 9),
                new("Felheart Gloves", 16805, 31971, 10),
            },
            ["T2"] = new Piece[]
            {
                new("Nemesis Skullcap", 16929, 34369, 1),
                new("Nemesis Spaulders", 16932, 34022, 3),
                new("Nemesis Robes", 16931, 34014, 20),
                new("Nemesis Belt", 16933, 34011, 6),
                new("Nemesis Leggings", 16930, 29857, 7),
                new("Nemesis Boots", 16927, 34015, 8),
                new("Nemesis Bracers", 16934, 34012, 9),
                new("Nemesis Gloves", 16928, 34013, 10),
            },
            ["T3"] = new Piece[]
            {
                new("Plagueheart Circlet", 22506, 35182, 1),
                new("Plagueheart Shoulderpads", 22507, 35187, 3),
                new("Plagueheart Robe", 22504, 35185, 20),
                new("Plagueheart Belt", 22510, 35179, 6),
                new("Plagueheart Leggings", 22505, 35184, 7),
                new("Plagueheart Sandals", 22508, 35186, 8),
                new("Plagueheart Bindings", 22511, 35180, 9),
                new("Plagueheart Gloves", 22509, 35183, 10),
                new("Plagueheart Ring", 23063, 35472, 11),
            },
        };
        sets["Warrior"] = new Dictionary<string, Piece[]>
        {
            ["T0"] = new Piece[]
            {
                new("Helm of Valor", 16731, 31284, 1),
                new("Spaulders of Valor", 16733, 29964, 3),
                new("Breastplate of Valor", 16730, 29958, 5),
                new("Belt of Valor", 16736, 29959, 6),
                new("Legplates of Valor", 16732, 29963, 7),
                new("Boots of Valor", 16734, 29960, 8),
                new("Bracers of Valor", 16735, 29961, 9),
                new("Gauntlets of Valor", 16737, 29962, 10),
            },
            ["T0.5"] = new Piece[]
            {
                new("Helm of Heroism", 21999, 34614, 1),
                new("Spaulders of Heroism", 22001, 34616, 3),
                new("Breastplate of Heroism", 21997, 34617, 5),
                new("Belt of Heroism", 21994, 34610, 6),
                new("Legplates of Heroism", 22000, 34615, 7),
                new("Boots of Heroism", 21995, 34611, 8),
                new("Bracers of Heroism", 21996, 34612, 9),
                new("Gauntlets of Heroism", 21998, 34613, 10),
            },
            ["T1"] = new Piece[]
            {
                new("Helm of Might", 16866, 31260, 1),
                new("Pauldrons of Might", 16868, 31024, 3),
                new("Breastplate of Might", 16865, 31021, 5),
                new("Belt of Might", 16864, 31019, 6),
                new("Legplates of Might", 16867, 31023, 7),
                new("Sabatons of Might", 16862, 31025, 8),
                new("Bracers of Might", 16861, 31020, 9),
                new("Gauntlets of Might", 16863, 31022, 10),
            },
            ["T2"] = new Piece[]
            {
                new("Helm of Wrath", 16963, 34215, 1),
                new("Pauldrons of Wrath", 16961, 34253, 3),
                new("Breastplate of Wrath", 16966, 33983, 5),
                new("Waistband of Wrath", 16960, 33990, 6),
                new("Legplates of Wrath", 16962, 33986, 7),
                new("Sabatons of Wrath", 16965, 33989, 8),
                new("Bracelets of Wrath", 16959, 33982, 9),
                new("Gauntlets of Wrath", 16964, 33984, 10),
            },
            ["T3"] = new Piece[]
            {
                new("Dreadnaught Helmet", 22418, 35447, 1),
                new("Dreadnaught Pauldrons", 22419, 35177, 3),
                new("Dreadnaught Breastplate", 22416, 35049, 5),
                new("Dreadnaught Waistguard", 22422, 35058, 6),
                new("Dreadnaught Legplates", 22417, 35051, 7),
                new("Dreadnaught Sabatons", 22420, 35067, 8),
                new("Dreadnaught Bracers", 22423, 35044, 9),
                new("Dreadnaught Gauntlets", 22421, 35050, 10),
            },
        };
        Sets = sets;
        Classes = new List<string>(sets.Keys).ToArray();
    }
}
