namespace MSUIClient.Net;

// 1.12.1 (client build 5875) opcodes. Values verified against
// benilla-protocol/src/messages/opcode.rs (which cites vmangos). This is the
// working subset for connect + entities + movement + combat; add more from
// opcode.rs as new packets are handled. Note: 1.12 has NO SMSG_HEALTH_UPDATE /
// SMSG_POWER_UPDATE / TIME_SYNC — health, power and stats all arrive as UNIT
// fields in SMSG_UPDATE_OBJECT.
public enum Op : ushort
{
    // --- Auth / session ---
    SMSG_AUTH_CHALLENGE          = 0x01EC,
    CMSG_AUTH_SESSION            = 0x01ED,
    SMSG_AUTH_RESPONSE           = 0x01EE,
    SMSG_WARDEN_DATA             = 0x02E6,
    CMSG_PING                    = 0x01DC,
    SMSG_PONG                    = 0x01DD,

    // --- Character select / login ---
    CMSG_CHAR_CREATE             = 0x0036,
    CMSG_CHAR_ENUM               = 0x0037,
    CMSG_CHAR_DELETE             = 0x0038,
    SMSG_CHAR_CREATE             = 0x003A,
    SMSG_CHAR_ENUM               = 0x003B,
    SMSG_CHAR_DELETE             = 0x003C,
    CMSG_PLAYER_LOGIN            = 0x003D,
    SMSG_NEW_WORLD               = 0x003E,
    SMSG_TRANSFER_PENDING        = 0x003F,
    SMSG_TRANSFER_ABORTED        = 0x0040,
    SMSG_CHARACTER_LOGIN_FAILED  = 0x0041,
    SMSG_LOGIN_SETTIMESPEED      = 0x0042,
    SMSG_LOGIN_VERIFY_WORLD      = 0x0236,
    CMSG_SET_ACTIVE_MOVER        = 0x026A,
    CMSG_LOGOUT_REQUEST          = 0x004B,
    SMSG_LOGOUT_RESPONSE         = 0x004C,
    SMSG_LOGOUT_COMPLETE         = 0x004D,
    CMSG_LOGOUT_CANCEL           = 0x004E,
    SMSG_LOGOUT_CANCEL_ACK       = 0x004F,
    SMSG_TRIGGER_CINEMATIC       = 0x00FA,
    CMSG_COMPLETE_CINEMATIC      = 0x00FC,
    SMSG_TUTORIAL_FLAGS          = 0x00FD,
    SMSG_GROUP_LIST              = 0x007D,
    CMSG_GROUP_INVITE            = 0x006E,
    SMSG_GROUP_INVITE            = 0x006F,
    CMSG_GROUP_ACCEPT            = 0x0072,
    CMSG_GROUP_DECLINE           = 0x0073,
    SMSG_GROUP_DECLINE           = 0x0074,
    CMSG_GROUP_UNINVITE          = 0x0075,
    CMSG_GROUP_UNINVITE_GUID     = 0x0076,
    SMSG_GROUP_UNINVITE          = 0x0077,
    CMSG_GROUP_SET_LEADER        = 0x0078,
    SMSG_GROUP_SET_LEADER        = 0x0079,
    CMSG_LOOT_METHOD             = 0x007A,
    CMSG_GROUP_DISBAND           = 0x007B,
    SMSG_GROUP_DESTROYED         = 0x007C,
    SMSG_PARTY_MEMBER_STATS      = 0x007E,
    SMSG_PARTY_COMMAND_RESULT    = 0x007F,
    MSG_MINIMAP_PING             = 0x01D5,
    CMSG_GROUP_CHANGE_SUB_GROUP  = 0x027E,
    CMSG_REQUEST_PARTY_MEMBER_STATS = 0x027F,
    CMSG_GROUP_SWAP_SUB_GROUP    = 0x0280,
    CMSG_GROUP_RAID_CONVERT      = 0x028E,
    CMSG_GROUP_ASSISTANT_LEADER  = 0x028F,
    SMSG_PARTY_MEMBER_STATS_FULL = 0x02F2,
    MSG_RAID_TARGET_UPDATE       = 0x0321,
    MSG_RAID_READY_CHECK         = 0x0322,
    CMSG_MOVE_WORLDPORT_ACK      = 0x00DC,
    CMSG_ZONEUPDATE              = 0x01F4,

    // --- Object updates ---
    SMSG_UPDATE_OBJECT           = 0x00A9,
    SMSG_DESTROY_OBJECT          = 0x00AA,
    SMSG_COMPRESSED_UPDATE_OBJECT = 0x01F6,

    // --- Queries ---
    CMSG_NAME_QUERY              = 0x0050,
    SMSG_NAME_QUERY_RESPONSE     = 0x0051,
    CMSG_WHO                     = 0x0062,
    SMSG_WHO                     = 0x0063,
    CMSG_FRIEND_LIST             = 0x0066,
    SMSG_FRIEND_LIST             = 0x0067,
    SMSG_FRIEND_STATUS           = 0x0068,
    CMSG_ADD_FRIEND              = 0x0069,
    CMSG_DEL_FRIEND              = 0x006A,
    SMSG_IGNORE_LIST             = 0x006B,
    CMSG_ADD_IGNORE              = 0x006C,
    CMSG_DEL_IGNORE              = 0x006D,
    CMSG_PET_SET_ACTION          = 0x0174,
    CMSG_PET_ACTION              = 0x0175,
    CMSG_PET_CANCEL_AURA         = 0x026B,
    SMSG_PET_SPELLS              = 0x0179,
    SMSG_PET_MODE                = 0x017A,
    SMSG_PET_CAST_FAILED         = 0x0138,
    SMSG_PET_ACTION_FEEDBACK     = 0x02C6,
    CMSG_PET_STOP_ATTACK         = 0x02EA,
    CMSG_INSPECT                 = 0x0114,
    SMSG_INSPECT                 = 0x0115,
    CMSG_CREATURE_QUERY          = 0x0060,
    SMSG_CREATURE_QUERY_RESPONSE = 0x0061,
    CMSG_GAMEOBJECT_QUERY        = 0x005E,
    SMSG_GAMEOBJECT_QUERY_RESPONSE = 0x005F,
    CMSG_ITEM_QUERY_SINGLE       = 0x0056,
    SMSG_ITEM_QUERY_SINGLE_RESPONSE = 0x0058,
    CMSG_QUEST_QUERY             = 0x005C,
    SMSG_QUEST_QUERY_RESPONSE    = 0x005D,

    // --- NPC gossip (1.12.1 Opcodes_1_12_1.h:380-385) ---
    CMSG_GOSSIP_HELLO             = 0x017B,
    CMSG_GOSSIP_SELECT_OPTION     = 0x017C,
    SMSG_GOSSIP_MESSAGE           = 0x017D,
    SMSG_GOSSIP_COMPLETE          = 0x017E,
    CMSG_NPC_TEXT_QUERY           = 0x017F,
    SMSG_NPC_TEXT_UPDATE          = 0x0180,

    // --- Game objects / readable world pages ---
    CMSG_PAGE_TEXT_QUERY          = 0x005A,
    SMSG_PAGE_TEXT_QUERY_RESPONSE = 0x005B,
    CMSG_GAMEOBJ_USE              = 0x00B1,
    SMSG_GAMEOBJECT_CUSTOM_ANIM   = 0x00B3,

    // --- Questing ---
    CMSG_QUESTGIVER_STATUS_QUERY   = 0x0182,
    SMSG_QUESTGIVER_STATUS         = 0x0183,
    CMSG_QUESTGIVER_HELLO          = 0x0184,
    SMSG_QUESTGIVER_QUEST_LIST     = 0x0185,
    CMSG_QUESTGIVER_QUERY_QUEST    = 0x0186,
    SMSG_QUESTGIVER_QUEST_DETAILS  = 0x0188,
    CMSG_QUESTGIVER_ACCEPT_QUEST   = 0x0189,
    CMSG_QUESTGIVER_COMPLETE_QUEST = 0x018A,
    SMSG_QUESTGIVER_REQUEST_ITEMS  = 0x018B,
    CMSG_QUESTGIVER_REQUEST_REWARD = 0x018C,
    SMSG_QUESTGIVER_OFFER_REWARD   = 0x018D,
    CMSG_QUESTGIVER_CHOOSE_REWARD  = 0x018E,
    SMSG_QUESTGIVER_QUEST_INVALID  = 0x018F,
    SMSG_QUESTGIVER_QUEST_COMPLETE = 0x0191,
    SMSG_QUESTGIVER_QUEST_FAILED   = 0x0192,
    CMSG_QUESTLOG_REMOVE_QUEST     = 0x0194,
    SMSG_QUESTLOG_FULL             = 0x0195,
    SMSG_QUESTUPDATE_FAILED        = 0x0196,
    SMSG_QUESTUPDATE_FAILEDTIMER   = 0x0197,
    SMSG_QUESTUPDATE_COMPLETE      = 0x0198,
    SMSG_QUESTUPDATE_ADD_KILL      = 0x0199,
    SMSG_QUESTUPDATE_ADD_ITEM      = 0x019A,

    // --- Vendor ---
    CMSG_LIST_INVENTORY           = 0x019E,
    SMSG_LIST_INVENTORY           = 0x019F,
    CMSG_SELL_ITEM                = 0x01A0,
    SMSG_SELL_ITEM                = 0x01A1,
    CMSG_BUY_ITEM                 = 0x01A2,
    CMSG_BUY_ITEM_IN_SLOT         = 0x01A3,
    SMSG_BUY_ITEM                 = 0x01A4,
    SMSG_BUY_FAILED               = 0x01A5,
    CMSG_BUYBACK_ITEM             = 0x0290,
    CMSG_REPAIR_ITEM              = 0x02A8,

    // --- Flightmaster / taxi ---
    CMSG_TAXINODE_STATUS_QUERY    = 0x01AA,
    SMSG_TAXINODE_STATUS          = 0x01AB,
    CMSG_TAXIQUERYAVAILABLENODES  = 0x01AC,
    SMSG_SHOWTAXINODES            = 0x01AD,
    CMSG_ACTIVATETAXI             = 0x01AE,
    SMSG_ACTIVATETAXIREPLY        = 0x01AF,

    // --- Trainer ---
    CMSG_TRAINER_LIST             = 0x01B0,
    SMSG_TRAINER_LIST             = 0x01B1,
    CMSG_TRAINER_BUY_SPELL        = 0x01B2,
    SMSG_TRAINER_BUY_SUCCEEDED    = 0x01B3,
    SMSG_TRAINER_BUY_FAILED       = 0x01B4,
    CMSG_BINDER_ACTIVATE          = 0x01B5,
    SMSG_BINDER_CONFIRM           = 0x01B6,
    CMSG_BANKER_ACTIVATE          = 0x01B7,
    SMSG_SHOW_BANK                = 0x01B8,
    CMSG_BUY_BANK_SLOT            = 0x01B9,
    SMSG_BUY_BANK_SLOT_RESULT     = 0x01BA,

    // --- Mail ---
    CMSG_SEND_MAIL                = 0x0238,
    SMSG_SEND_MAIL_RESULT         = 0x0239,
    CMSG_GET_MAIL_LIST            = 0x023A,
    SMSG_MAIL_LIST_RESULT         = 0x023B,
    CMSG_ITEM_TEXT_QUERY          = 0x0243,
    SMSG_ITEM_TEXT_QUERY_RESPONSE = 0x0244,
    CMSG_MAIL_TAKE_MONEY          = 0x0245,
    CMSG_MAIL_TAKE_ITEM           = 0x0246,
    CMSG_MAIL_MARK_AS_READ        = 0x0247,
    CMSG_MAIL_RETURN_TO_SENDER    = 0x0248,
    CMSG_MAIL_DELETE              = 0x0249,
    CMSG_MAIL_CREATE_TEXT_ITEM    = 0x024A,
    MSG_QUERY_NEXT_MAIL_TIME      = 0x0284,
    SMSG_RECEIVED_MAIL            = 0x0285,
    CMSG_GMTICKET_CREATE          = 0x0205,
    SMSG_GMTICKET_CREATE          = 0x0206,
    CMSG_GMTICKET_UPDATETEXT      = 0x0207,
    SMSG_GMTICKET_UPDATETEXT      = 0x0208,
    CMSG_GMTICKET_GETTICKET       = 0x0211,
    SMSG_GMTICKET_GETTICKET       = 0x0212,
    CMSG_GMTICKET_DELETETICKET    = 0x0217,
    SMSG_GMTICKET_DELETETICKET    = 0x0218,
    CMSG_GMTICKET_SYSTEMSTATUS    = 0x021A,
    SMSG_GMTICKET_SYSTEMSTATUS    = 0x021B,

    // --- Auction house ---
    MSG_AUCTION_HELLO             = 0x0255,
    CMSG_AUCTION_SELL_ITEM        = 0x0256,
    CMSG_AUCTION_REMOVE_ITEM      = 0x0257,
    CMSG_AUCTION_LIST_ITEMS       = 0x0258,
    CMSG_AUCTION_LIST_OWNER_ITEMS = 0x0259,
    CMSG_AUCTION_PLACE_BID        = 0x025A,
    SMSG_AUCTION_COMMAND_RESULT   = 0x025B,
    SMSG_AUCTION_LIST_RESULT      = 0x025C,
    SMSG_AUCTION_OWNER_LIST_RESULT = 0x025D,
    SMSG_AUCTION_BIDDER_NOTIFICATION = 0x025E,
    SMSG_AUCTION_OWNER_NOTIFICATION = 0x025F,
    CMSG_AUCTION_LIST_BIDDER_ITEMS = 0x0264,
    SMSG_AUCTION_BIDDER_LIST_RESULT = 0x0265,
    SMSG_AUCTION_REMOVED_NOTIFICATION = 0x028D,

    // --- Guild ---
    CMSG_GUILD_QUERY              = 0x0054,
    SMSG_GUILD_QUERY_RESPONSE     = 0x0055,
    CMSG_GUILD_CREATE             = 0x0081,
    CMSG_GUILD_INVITE             = 0x0082,
    SMSG_GUILD_INVITE             = 0x0083,
    CMSG_GUILD_ACCEPT             = 0x0084,
    CMSG_GUILD_DECLINE            = 0x0085,
    SMSG_GUILD_INFO               = 0x0088,
    CMSG_GUILD_ROSTER             = 0x0089,
    SMSG_GUILD_ROSTER             = 0x008A,
    CMSG_GUILD_PROMOTE            = 0x008B,
    CMSG_GUILD_DEMOTE             = 0x008C,
    CMSG_GUILD_LEAVE              = 0x008D,
    CMSG_GUILD_REMOVE             = 0x008E,
    CMSG_GUILD_DISBAND            = 0x008F,
    CMSG_GUILD_LEADER             = 0x0090,
    CMSG_GUILD_MOTD               = 0x0091,
    SMSG_GUILD_EVENT              = 0x0092,
    SMSG_GUILD_COMMAND_RESULT     = 0x0093,
    MSG_SAVE_GUILD_EMBLEM         = 0x01F1,
    SMSG_TABARDVENDOR_ACTIVATE    = 0x01F2,

    // --- Talents ---
    CMSG_UNLEARN_TALENTS          = 0x0213,
    CMSG_LEARN_TALENT             = 0x0251,
    MSG_TALENT_WIPE_CONFIRM       = 0x02AA,

    // --- Skills ---
    CMSG_UNLEARN_SKILL            = 0x0202,

    // --- Movement (MSG_* are bidirectional) ---
    MSG_MOVE_START_FORWARD       = 0x00B5,
    MSG_MOVE_START_BACKWARD      = 0x00B6,
    MSG_MOVE_STOP                = 0x00B7,
    MSG_MOVE_START_STRAFE_LEFT   = 0x00B8,
    MSG_MOVE_START_STRAFE_RIGHT  = 0x00B9,
    MSG_MOVE_STOP_STRAFE         = 0x00BA,
    MSG_MOVE_JUMP                = 0x00BB,
    MSG_MOVE_START_TURN_LEFT     = 0x00BC,
    MSG_MOVE_START_TURN_RIGHT    = 0x00BD,
    MSG_MOVE_STOP_TURN           = 0x00BE,
    MSG_MOVE_FALL_LAND           = 0x00C9,
    MSG_MOVE_START_SWIM          = 0x00CA,
    MSG_MOVE_STOP_SWIM           = 0x00CB,
    MSG_MOVE_SET_FACING          = 0x00DA,
    MSG_MOVE_HEARTBEAT           = 0x00EE,
    MSG_MOVE_TELEPORT_ACK        = 0x00C7,
    SMSG_MONSTER_MOVE            = 0x00DD,
    CMSG_MOVE_SPLINE_DONE        = 0x02C9,
    SMSG_FORCE_RUN_SPEED_CHANGE  = 0x00E2,
    CMSG_FORCE_RUN_SPEED_CHANGE_ACK = 0x00E3,
    SMSG_FORCE_MOVE_ROOT         = 0x00E8,
    CMSG_FORCE_MOVE_ROOT_ACK     = 0x00E9,
    SMSG_FORCE_MOVE_UNROOT       = 0x00EA,
    CMSG_FORCE_MOVE_UNROOT_ACK   = 0x00EB,

    // --- Combat / spells ---
    CMSG_SET_SELECTION           = 0x013D,
    CMSG_ATTACKSWING             = 0x0141,
    CMSG_ATTACKSTOP              = 0x0142,
    CMSG_SETSHEATHED             = 0x01E0,
    SMSG_ATTACKSTART             = 0x0143,
    SMSG_ATTACKSTOP              = 0x0144,
    SMSG_ATTACKSWING_NOTINRANGE  = 0x0145,
    SMSG_ATTACKSWING_BADFACING   = 0x0146,
    SMSG_ATTACKSWING_NOTSTANDING = 0x0147,
    SMSG_ATTACKSWING_DEADTARGET  = 0x0148,
    SMSG_ATTACKSWING_CANT_ATTACK = 0x0149,
    SMSG_ATTACKERSTATEUPDATE     = 0x014A,
    SMSG_AI_REACTION             = 0x013C,
    SMSG_SPELLHEALLOG            = 0x0150,
    SMSG_SPELLENERGIZELOG        = 0x0151,
    SMSG_LOG_XPGAIN              = 0x01D0,
    SMSG_LEVELUP_INFO            = 0x01D4,
    SMSG_ENVIRONMENTALDAMAGELOG  = 0x01FC,
    SMSG_SPELLLOGMISS            = 0x024B,
    SMSG_PERIODICAURALOG         = 0x024E,
    SMSG_SPELLDAMAGESHIELD       = 0x024F,
    SMSG_SPELLNONMELEEDAMAGELOG  = 0x0250,
    CMSG_CAST_SPELL              = 0x012E,
    CMSG_CANCEL_CAST             = 0x012F,
    CMSG_CANCEL_AURA             = 0x0136,
    SMSG_UPDATE_AURA_DURATION    = 0x0137,
    CMSG_CANCEL_CHANNELLING      = 0x013B,
    CMSG_CANCEL_AUTO_REPEAT_SPELL = 0x026D,
    CMSG_SET_ACTION_BUTTON       = 0x0128,
    CMSG_USE_ITEM                = 0x00AB,
    CMSG_AUTOEQUIP_ITEM          = 0x010A,
    CMSG_SWAP_ITEM               = 0x010C,
    CMSG_SWAP_INV_ITEM           = 0x010D,
    CMSG_SPLIT_ITEM              = 0x010E,
    CMSG_SET_AMMO                = 0x0268,
    SMSG_CAST_RESULT             = 0x0130,
    SMSG_SPELL_START             = 0x0131,
    SMSG_SPELL_GO                = 0x0132,
    SMSG_SPELL_COOLDOWN          = 0x0134,
    MSG_CHANNEL_START            = 0x0139,
    MSG_CHANNEL_UPDATE           = 0x013A,
    SMSG_SPELL_DELAYED           = 0x01E2,
    SMSG_SPELL_FAILED_OTHER      = 0x02A6,
    SMSG_PLAY_SPELL_VISUAL       = 0x01F3,
    SMSG_CANCEL_AUTO_REPEAT      = 0x029C,

    // --- Death / resurrection ---
    CMSG_REPOP_REQUEST           = 0x015A,
    SMSG_RESURRECT_REQUEST       = 0x015B,
    CMSG_RESURRECT_RESPONSE      = 0x015C,
    CMSG_RECLAIM_CORPSE          = 0x01D2,
    CMSG_SPIRIT_HEALER_ACTIVATE  = 0x021C,
    SMSG_CORPSE_RECLAIM_DELAY    = 0x0269,

    // --- Loot (solo corpse loot family; values verified vs vmangos Opcodes_1_12_1.h
    //     via benilla-protocol opcode.rs: 264, 349-355, 357-358) ---
    CMSG_AUTOSTORE_LOOT_ITEM     = 0x0108,
    CMSG_LOOT                    = 0x015D,
    CMSG_LOOT_MONEY              = 0x015E,
    CMSG_LOOT_RELEASE            = 0x015F,
    SMSG_LOOT_RESPONSE           = 0x0160,
    SMSG_LOOT_RELEASE_RESPONSE   = 0x0161,
    SMSG_LOOT_REMOVED            = 0x0162,
    SMSG_LOOT_MONEY_NOTIFY       = 0x0163,
    SMSG_LOOT_CLEAR_MONEY        = 0x0165,
    SMSG_ITEM_PUSH_RESULT        = 0x0166,

    // --- Misc world state seen at login (parsed leniently / ignored for now) ---
    SMSG_INITIAL_SPELLS          = 0x012A,
    SMSG_ACTION_BUTTONS          = 0x0129,
    SMSG_LEARNED_SPELL           = 0x012B,
    SMSG_SUPERCEDED_SPELL        = 0x012C,
    SMSG_REMOVED_SPELL           = 0x0203,
    SMSG_INITIALIZE_FACTIONS     = 0x0122,
    SMSG_SET_FACTION_VISIBLE     = 0x0123,
    SMSG_SET_FACTION_STANDING    = 0x0124,
    CMSG_INITIATE_TRADE          = 0x0116,
    CMSG_BEGIN_TRADE             = 0x0117,
    CMSG_ACCEPT_TRADE            = 0x011A,
    CMSG_UNACCEPT_TRADE          = 0x011B,
    CMSG_CANCEL_TRADE            = 0x011C,
    CMSG_SET_TRADE_ITEM          = 0x011D,
    CMSG_CLEAR_TRADE_ITEM        = 0x011E,
    CMSG_SET_TRADE_GOLD          = 0x011F,
    SMSG_TRADE_STATUS            = 0x0120,
    SMSG_TRADE_STATUS_EXTENDED   = 0x0121,
    SMSG_BINDPOINTUPDATE         = 0x0155,
    SMSG_INIT_WORLD_STATES       = 0x02C2,
    SMSG_UPDATE_WORLD_STATE      = 0x02C3,
    CMSG_MESSAGECHAT             = 0x0095,
    SMSG_MESSAGECHAT             = 0x0096,
    SMSG_NOTIFICATION            = 0x01CB,
    SMSG_EMOTE                   = 0x0103,
    SMSG_TEXT_EMOTE              = 0x0105,

    // --- SuperUI CRPG/RTS control extension (SuperUI-Core fork only; above the
    // vanilla table, see docs/SUI_WIRE_PROTOCOL.md in SuperUI-Core) ---
    CMSG_SUI_CONTROL_REQUEST     = 0x033C,
    CMSG_SUI_CONTROL_RELEASE     = 0x033D,
    CMSG_SUI_ORDER               = 0x033E,
    SMSG_SUI_CONTROL_ROSTER      = 0x033F,
    SMSG_SUI_CONTROL_ACK         = 0x0340,
    SMSG_SUI_PROXY               = 0x0341,
    SMSG_SUI_SNAPSHOT            = 0x0342,
    CMSG_SUI_CAM                 = 0x0343,
}
