namespace MSUIClient.Net;

/// <summary>Complete build-5875 SpellCastResult table (0x00..0x91).</summary>
public static class SpellCastResultNames
{
    private static readonly string[] Names =
    [
        "AFFECTING_COMBAT", "ALREADY_AT_FULL_HEALTH", "ALREADY_AT_FULL_POWER",
        "ALREADY_BEING_TAMED", "ALREADY_HAVE_CHARM", "ALREADY_HAVE_SUMMON", "ALREADY_OPEN",
        "AURA_BOUNCED", "AUTOTRACK_INTERRUPTED", "BAD_IMPLICIT_TARGETS", "BAD_TARGETS",
        "CANT_BE_CHARMED", "CANT_BE_DISENCHANTED", "CANT_BE_PROSPECTED", "CANT_CAST_ON_TAPPED",
        "CANT_DUEL_WHILE_INVISIBLE", "CANT_DUEL_WHILE_STEALTHED", "CANT_STEALTH",
        "CASTER_AURASTATE", "CASTER_DEAD", "CHARMED", "CHEST_IN_USE", "CONFUSED", "DONT_REPORT",
        "EQUIPPED_ITEM", "EQUIPPED_ITEM_CLASS", "EQUIPPED_ITEM_CLASS_MAINHAND",
        "EQUIPPED_ITEM_CLASS_OFFHAND", "ERROR", "FIZZLE", "FLEEING", "FOOD_LOWLEVEL", "HIGHLEVEL",
        "HUNGER_SATIATED", "IMMUNE", "INTERRUPTED", "INTERRUPTED_COMBAT", "ITEM_ALREADY_ENCHANTED",
        "ITEM_GONE", "ITEM_NOT_FOUND", "ITEM_NOT_READY", "LEVEL_REQUIREMENT", "LINE_OF_SIGHT", "LOWLEVEL",
        "LOW_CASTLEVEL", "MAINHAND_EMPTY", "MOVING", "NEED_AMMO", "NEED_AMMO_POUCH",
        "NEED_EXOTIC_AMMO", "NOPATH", "NOT_BEHIND", "NOT_FISHABLE", "NOT_HERE", "NOT_INFRONT",
        "NOT_IN_CONTROL", "NOT_KNOWN", "NOT_MOUNTED", "NOT_ON_TAXI", "NOT_ON_TRANSPORT", "NOT_READY",
        "NOT_SHAPESHIFT", "NOT_STANDING", "NOT_TRADEABLE", "NOT_TRADING", "NOT_UNSHEATHED",
        "NOT_WHILE_GHOST", "NO_AMMO", "NO_CHARGES_REMAIN", "NO_CHAMPION", "NO_COMBO_POINTS",
        "NO_DUELING", "NO_ENDURANCE", "NO_FISH", "NO_ITEMS_WHILE_SHAPESHIFTED", "NO_MOUNTS_ALLOWED",
        "NO_PET", "NO_POWER", "NOTHING_TO_DISPEL", "NOTHING_TO_STEAL", "ONLY_ABOVEWATER",
        "ONLY_DAYTIME", "ONLY_INDOORS", "ONLY_MOUNTED", "ONLY_NIGHTTIME", "ONLY_OUTDOORS",
        "ONLY_SHAPESHIFT", "ONLY_STEALTHED", "ONLY_UNDERWATER", "OUT_OF_RANGE", "PACIFIED", "POSSESSED",
        "REAGENTS", "REQUIRES_AREA", "REQUIRES_SPELL_FOCUS", "ROOTED", "SILENCED", "SPELL_IN_PROGRESS",
        "SPELL_LEARNED", "SPELL_UNAVAILABLE", "STUNNED", "TARGETS_DEAD", "TARGET_AFFECTING_COMBAT",
        "TARGET_AURASTATE", "TARGET_DUELING", "TARGET_ENEMY", "TARGET_ENRAGED", "TARGET_FRIENDLY",
        "TARGET_IN_COMBAT", "TARGET_IS_PLAYER", "TARGET_NOT_DEAD", "TARGET_NOT_IN_PARTY",
        "TARGET_NOT_LOOTED", "TARGET_NOT_PLAYER", "TARGET_NO_POCKETS", "TARGET_NO_WEAPONS",
        "TARGET_UNSKINNABLE", "THIRST_SATIATED", "TOO_CLOSE", "TOO_MANY_OF_ITEM", "TOTEMS",
        "TRAINING_POINTS", "TRY_AGAIN", "UNIT_NOT_BEHIND", "UNIT_NOT_INFRONT", "WRONG_PET_FOOD",
        "NOT_WHILE_FATIGUED", "TARGET_NOT_IN_INSTANCE", "NOT_WHILE_TRADING", "TARGET_NOT_IN_RAID",
        "DISENCHANT_WHILE_LOOTING", "PROSPECT_WHILE_LOOTING", "PROSPECT_NEED_MORE", "TARGET_FREEFORALL",
        "NO_EDIBLE_CORPSES", "ONLY_BATTLEGROUNDS", "TARGET_NOT_GHOST", "TOO_MANY_SKILLS",
        "TRANSFORM_UNUSABLE", "WRONG_WEATHER", "DAMAGE_IMMUNE", "PREVENTED_BY_MECHANIC", "PLAY_TIME",
        "REPUTATION", "MIN_SKILL", "UNKNOWN",
    ];

    public static string Name(byte reason) => reason < Names.Length
        ? $"SPELL_FAILED_{Names[reason]}" : $"SPELL_FAILED_0x{reason:X2}";

    public static string Text(byte reason, string powerName = "power") => reason switch
    {
        0x00 => "You are in combat.", 0x01 => "You are already at full health.",
        0x02 => $"You are already at full {powerName.ToLowerInvariant()}.",
        0x03 => "That creature is already being tamed.", 0x04 => "You already control a charmed creature.",
        0x05 => "You already control a summoned creature.", 0x06 => "Already open.",
        0x07 => "A more powerful spell is already active.", 0x08 or 0x17 or 0x21 or 0x5C or 0x75 or 0x78 or 0x84 => "",
        0x09 => "You have no target.", 0x0A => "Invalid target.", 0x0B => "Target cannot be charmed.",
        0x0C => "Item cannot be disenchanted.", 0x0D => "There are no gems in this.",
        0x0E => "Target is tapped.", 0x0F => "You cannot start a duel while invisible.",
        0x10 => "You cannot start a duel while stealthed.", 0x11 => "You are too close to enemies.",
        0x12 or 0x67 => "You cannot do that yet.", 0x13 => "You are dead.",
        0x14 => "Cannot do that while charmed.", 0x15 => "That is already being used.",
        0x16 => "Cannot do that while confused.", 0x18 => "You must have the proper item equipped.",
        0x19 => "You must have the proper item class equipped.",
        0x1A => "You must have the proper item equipped in the main hand.",
        0x1B => "You must have the proper item equipped in the off hand.", 0x1C => "Internal error.",
        0x1D => "Fizzled.", 0x1E => "Cannot do that while fleeing.",
        0x1F => "That food's level is not high enough for your pet.", 0x20 => "Target is too high level.",
        0x22 => "Immune.", 0x23 or 0x24 => "Interrupted.", 0x25 => "Item is already enchanted.",
        0x26 => "Item is gone.", 0x27 => "Item not found.", 0x28 => "Item is not ready yet.",
        0x29 => "You are not high enough level.", 0x2A => "Target not in line of sight.",
        0x2B => "Target is too low level.", 0x2C => "Skill not high enough.",
        0x2D => "Your weapon hand is empty.", 0x2E => "Cannot do that while moving.",
        0x2F => "Ammo must be in the ammo slot before it can be fired.", 0x30 => "Requires an ammo pouch.",
        0x31 => "Requires exotic ammo.", 0x32 => "No path available.",
        0x33 => "You must be behind your target.", 0x34 => "Your cast did not land in fishable water.",
        0x35 => "You cannot use that here.", 0x36 => "You must be in front of your target.",
        0x37 => "You are not in control of your actions.", 0x38 => "Spell not learned.",
        0x39 => "You are mounted.", 0x3A => "You are in flight.", 0x3B => "You are on a transport.",
        0x3C => "Spell is not ready yet.", 0x3D => "You are in shapeshift form.",
        0x3E => "You must be standing to do that.", 0x3F => "You can only use this on an object you own.",
        0x40 => "You are not trading.", 0x41 => "You have to be unsheathed to do that.",
        0x42 => "Cannot cast as a ghost.", 0x43 => "Out of ammo.", 0x44 => "No charges remain.",
        0x45 => "You have not selected a champion.", 0x46 => "That ability requires combo points.",
        0x47 => "Dueling is not allowed here.", 0x48 => "Not enough endurance.",
        0x49 => "There are no fish here.", 0x4A => "Cannot use items while shapeshifted.",
        0x4B => "You cannot mount here.", 0x4C => "You do not have a pet.",
        0x4D => $"Not enough {powerName.ToLowerInvariant()}.", 0x4E => "Nothing to dispel.",
        0x4F => "Nothing to steal.", 0x50 => "Cannot use while swimming.",
        0x51 => "Can only use during the day.", 0x52 => "Can only use indoors.",
        0x53 => "Can only use while mounted.", 0x54 => "Can only use during the night.",
        0x55 => "Can only use outside.", 0x56 => "You are in the wrong form.",
        0x57 => "You must be in stealth mode.", 0x58 => "Can only use while swimming.",
        0x59 => "Out of range.", 0x5A => "Cannot use that ability while pacified.",
        0x5B => "You are possessed.", 0x5D => "You are not in the required area.",
        0x5E => "Requires a spell focus.", 0x5F => "You are unable to move.",
        0x60 => "Cannot do that while silenced.", 0x61 => "Another action is in progress.",
        0x62 => "You have already learned the spell.", 0x63 => "The spell is not available to you.",
        0x64 => "Cannot do that while stunned.", 0x65 => "Your target is dead.",
        0x66 => "Target is in combat.", 0x68 => "Target is currently dueling.",
        0x69 => "Target is hostile.", 0x6A => "Target is too enraged to be charmed.",
        0x6B => "Target is friendly.", 0x6C => "The target cannot be in combat.",
        0x6D => "Cannot target players.", 0x6E => "Target is alive.",
        0x6F => "Target is not in your party.", 0x70 => "Creature must be looted first.",
        0x71 => "Target is not a player.", 0x72 => "No pockets to pick.",
        0x73 => "Target has no weapons equipped.", 0x74 => "Creature is not skinnable.",
        0x76 => "Target too close.", 0x77 => "You have too many of that item already.",
        0x79 => "Not enough training points.", 0x7A => "Failed attempt.",
        0x7B => "Target needs to be behind you.", 0x7C => "Target needs to be in front of you.",
        0x7D => "Your pet does not like that food.", 0x7E => "Cannot cast while fatigued.",
        0x7F => "Target must be in this instance.", 0x80 => "Cannot cast while trading.",
        0x81 => "Target is not in your party or raid group.", 0x82 => "Cannot disenchant while looting.",
        0x83 => "Cannot prospect while looting.", 0x85 => "Target is in free-for-all PvP combat.",
        0x86 => "There are no nearby corpses to eat.", 0x87 => "Can only use in battlegrounds.",
        0x88 => "Target is not a ghost.", 0x89 => "Your pet cannot learn any more skills.",
        0x8A => "You cannot use the new item.", 0x8B => "The weather is not right for that.",
        0x8C => "You cannot do that while you are immune.", 0x8D => "Prevented by a game mechanic.",
        0x8E => "Maximum play time exceeded.", 0x8F => "Your reputation is not high enough.",
        0x90 => "Your skill is not high enough.", _ => "Spell failed.",
    };
}
