using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace MSUIClient.World.Encounters;

// ─────────────────────────────────────────────────────────────────────────────
// Authored encounters live on disk as JSON — never as C#.
//
// This is the load-bearing decision of the whole design. The instant an
// encounter is expressed in a real programming language it becomes opaque to
// the tool that is supposed to visualise it, and we are back to reverse-
// engineering compiled behaviour. A JSON document can be read, diffed, reviewed,
// generated by an authoring UI, and eventually emitted as DB rows for a server
// interpreter to execute. Code can do none of that.
//
// An explicit DTO layer sits between the file and the runtime model on purpose:
// the file format has to survive refactors of the records behind it, so the two
// are allowed to drift and the mapping is written out by hand.
// ─────────────────────────────────────────────────────────────────────────────

/// <summary>Vector3 as a compact [x, y, z] array — far easier to eyeball in a diff
/// than three named properties, and it matches how coordinates are quoted in the
/// world DB and in the C++ scripts these documents are transcribed from.</summary>
public sealed class Vector3ArrayConverter : JsonConverter<Vector3>
{
    public override Vector3 Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartArray)
            throw new JsonException("expected [x, y, z]");
        Span<float> values = stackalloc float[3];
        int count = 0;
        while (reader.Read() && reader.TokenType != JsonTokenType.EndArray)
            if (count < 3) values[count++] = reader.GetSingle();
        return new Vector3(values[0], values[1], values[2]);
    }

    public override void Write(Utf8JsonWriter writer, Vector3 value, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        writer.WriteNumberValue(value.X);
        writer.WriteNumberValue(value.Y);
        writer.WriteNumberValue(value.Z);
        writer.WriteEndArray();
    }
}

// ── file-format DTOs (mutable, defaulted, tolerant) ──────────────────────────

public sealed class EncounterFileDto
{
    public int SchemaVersion { get; set; } = EncounterSchema.Version;
    public string Key { get; set; } = "";
    public string Name { get; set; } = "";
    public uint PrimaryEntry { get; set; }
    public List<uint>? MemberEntries { get; set; }
    public List<int>? MapIds { get; set; }
    public string? Note { get; set; }
    public ProvenanceDto? Provenance { get; set; }
    public List<string>? Coverage { get; set; }
    public List<ActorDto>? Actors { get; set; }
    public List<PhaseDto>? Phases { get; set; }
    public List<AbilityDto>? Abilities { get; set; }
}

public sealed class ProvenanceDto
{
    public string Source { get; set; } = "authored";
    public string? CoreBuildHash { get; set; }
    public string? DbRevision { get; set; }
    public int? ContentPatch { get; set; }
    public DateTime? CapturedUtc { get; set; }
}

public sealed class ActorDto
{
    public string Key { get; set; } = "";
    public string Name { get; set; } = "";
    public uint Entry { get; set; }
    public EncounterActorRole Role { get; set; } = EncounterActorRole.Friendly;
    public Vector3 Position { get; set; }
    public float Facing { get; set; }
    public float BoundingRadius { get; set; } = 0.5f;
    public float CombatReach { get; set; } = 1.5f;
    public uint Level { get; set; } = 60;
    public uint MaxHealth { get; set; } = 1000;
    public uint DisplayId { get; set; }
    public float DisplayScale { get; set; } = 1f;
    public List<MoveDto>? Moves { get; set; }
    public float Dps { get; set; }
    public RaidJob Job { get; set; } = RaidJob.None;
    public IdleMovementDto? IdleMovement { get; set; }
    public float RunSpeedYdPerSec { get; set; }
    public float WalkSpeedYdPerSec { get; set; }
    public float DetectionRangeYards { get; set; }
    public PlayerRulesDto? PlayerRules { get; set; }
}

public sealed class PlayerRulesDto
{
    public bool AlwaysFaceBoss { get; set; }
    public CombatPlanDto? Plan { get; set; }
}

public sealed class CombatPlanDto
{
    public string Name { get; set; } = "Custom plan";
    public CombatMovementDto? Movement { get; set; }
    public CombatEngagementMode Engagement { get; set; } = CombatEngagementMode.NeverInitiate;
    public List<CombatSupportPriorityDto>? SupportPriorities { get; set; }
    public List<CombatEnemyPriorityDto>? EnemyPriorities { get; set; }
    public List<CombatResponsibility>? Responsibilities { get; set; }
    public CombatResourcePolicyDto? Resources { get; set; }
    public CombatFallback Fallback { get; set; } = CombatFallback.ClassDefaults;
    public List<CombatAbilityIntentDto>? Rotation { get; set; }
    public uint ClassId { get; set; }
}

public sealed class CombatAbilityIntentDto
{
    public uint SpellId { get; set; }
    public string Name { get; set; } = "";
    public bool Enabled { get; set; } = true;
}

public sealed class CombatMovementDto
{
    public CombatMovementMode Mode { get; set; } = CombatMovementMode.Independent;
    public CombatSubjectDto? Anchor { get; set; }
    public float MinRangeYards { get; set; } = 8f;
    public float MaxRangeYards { get; set; } = 18f;
    public bool FacePrimaryEnemy { get; set; }
}

public sealed class CombatSubjectDto
{
    public CombatSubjectKind Kind { get; set; } = CombatSubjectKind.Self;
    public RaidJob Role { get; set; } = RaidJob.None;
    public int Ordinal { get; set; } = 1;
}

public sealed class CombatSupportPriorityDto
{
    public CombatSubjectDto Target { get; set; } = new();
    public float OnlyWhenBelowHealthPercent { get; set; } = 100f;
    public bool Enabled { get; set; } = true;
}

public sealed class CombatEnemyPriorityDto
{
    public CombatEnemyKind Kind { get; set; } = CombatEnemyKind.PrimaryEnemy;
    public bool Enabled { get; set; } = true;
}

public sealed class CombatResourcePolicyDto
{
    public int ReservePercent { get; set; } = 20;
    public int EmergencyHealthPercent { get; set; } = 25;
    public bool SaveMajorCooldowns { get; set; } = true;
}

public sealed class IdleMovementDto
{
    public IdleMovementKind Kind { get; set; } = IdleMovementKind.Stationary;
    public float WanderYards { get; set; }
    public List<IdleWaypointDto>? Points { get; set; }
    public string? Note { get; set; }
}

public sealed class IdleWaypointDto
{
    public Vector3 Position { get; set; }
    public int WaitMs { get; set; }
}

public sealed class MoveDto
{
    public int TimeMs { get; set; }
    public Vector3 Position { get; set; }
    public MoveAnchor Anchor { get; set; } = MoveAnchor.AtTime;
    public string? PhaseKey { get; set; }
    /// <summary>Radians; null = keep the facing the run ended with. Nullable because
    /// JSON has no NaN — the runtime struct uses NaN for the same "unset".</summary>
    public float? ArrivalFacing { get; set; }
    public bool Teleport { get; set; }
}

public sealed class TriggerDto
{
    public EncounterTriggerKind Kind { get; set; } = EncounterTriggerKind.Manual;
    public float Threshold { get; set; }
    public int Param1 { get; set; }
    public int Param2 { get; set; }
}

public sealed class TimingDto
{
    public int InitialMinMs { get; set; }
    public int InitialMaxMs { get; set; }
    public int RepeatMinMs { get; set; }
    public int RepeatMaxMs { get; set; }
}

public sealed class TargetDto
{
    public EncounterTargetKind Kind { get; set; } = EncounterTargetKind.CurrentVictim;
    public Vector3 Point { get; set; }
    public uint Param1 { get; set; }
}

public sealed class GeometryDto
{
    public FootprintKind Kind { get; set; } = FootprintKind.None;
    public float Radius { get; set; }
    public float ConeDegrees { get; set; }
    public float Width { get; set; }
    public float ProjectileSpeed { get; set; }
    public int DurationMs { get; set; }
    public List<Vector3>? Points { get; set; }
    public List<uint>? PointSpellIds { get; set; }
}

public sealed class StepDto
{
    public EncounterStepKind Kind { get; set; }
    public int DurationMs { get; set; }
    public Vector3 Point { get; set; }
    public uint SpellId { get; set; }
    public uint Entry { get; set; }
    public int Count { get; set; }
    public float Value { get; set; }
    public bool Flag { get; set; }
    public string? PhaseKey { get; set; }
    public string? Note { get; set; }
    public uint DisplayId { get; set; }
}

public sealed class SourceDto
{
    public string Kind { get; set; } = "authored";
    public string Location { get; set; } = "";
    public string? Detail { get; set; }
}

public sealed class AbilityDto
{
    public string Key { get; set; } = "";
    public string Name { get; set; } = "";
    public uint SpellId { get; set; }
    public TriggerDto? Trigger { get; set; }
    public TimingDto? Timing { get; set; }
    public TargetDto? Target { get; set; }
    public GeometryDto? Geometry { get; set; }
    public EncounterFidelity Fidelity { get; set; } = EncounterFidelity.Heuristic;
    public List<string>? Phases { get; set; }
    public int ChancePercent { get; set; } = 100;
    public int CastTimeMs { get; set; }
    public List<StepDto>? Steps { get; set; }
    public List<SourceDto>? Sources { get; set; }
    public string? Note { get; set; }
}

public sealed class TransitionDto
{
    public string ToPhase { get; set; } = "";
    public TriggerDto? Trigger { get; set; }
    public EncounterFidelity Fidelity { get; set; } = EncounterFidelity.Heuristic;
    public List<StepDto>? Steps { get; set; }
    public List<SourceDto>? Sources { get; set; }
    public string? Note { get; set; }
}

public sealed class PhaseDto
{
    public string Key { get; set; } = "";
    public string Name { get; set; } = "";
    public bool CasterFlying { get; set; }
    public bool MeleeEnabled { get; set; } = true;
    public List<StepDto>? OnEnter { get; set; }
    public List<TransitionDto>? Transitions { get; set; }
    public string? Note { get; set; }
}

/// <summary>Loads and saves authored encounter documents.</summary>
public sealed class EncounterLibrary
{
    public static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(), new Vector3ArrayConverter() },
    };

    private readonly Dictionary<string, EncounterDefinition> _byKey = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<uint, string> _byEntry = [];
    private readonly List<string> _errors = [];

    public string Directory { get; }
    public IReadOnlyCollection<EncounterDefinition> All => _byKey.Values;
    public IReadOnlyList<string> Errors => _errors;
    public int Count => _byKey.Count;

    public EncounterLibrary(string directory) => Directory = directory;

    public EncounterDefinition? Get(string key) => _byKey.GetValueOrDefault(key);

    /// <summary>An authored document for this creature entry, if one exists. Checked
    /// before falling back to a DB-derived definition.</summary>
    public EncounterDefinition? ForEntry(uint entry) =>
        _byEntry.TryGetValue(entry, out string? key) ? _byKey.GetValueOrDefault(key) : null;

    /// <summary>Reload every *.json in the directory. Bad documents are collected in
    /// <see cref="Errors"/> rather than thrown — one broken file must not take the
    /// whole library down.</summary>
    public int Reload()
    {
        _byKey.Clear();
        _byEntry.Clear();
        _errors.Clear();
        if (!System.IO.Directory.Exists(Directory)) return 0;

        foreach (string path in System.IO.Directory.EnumerateFiles(Directory, "*.json"))
        {
            try
            {
                EncounterFileDto? dto = JsonSerializer.Deserialize<EncounterFileDto>(
                    File.ReadAllText(path), JsonOptions);
                if (dto is null) { _errors.Add($"{Path.GetFileName(path)}: empty document"); continue; }
                if (dto.SchemaVersion != EncounterSchema.Version)
                {
                    _errors.Add($"{Path.GetFileName(path)}: schemaVersion {dto.SchemaVersion} " +
                                $"(this build reads {EncounterSchema.Version})");
                    continue;
                }
                EncounterDefinition definition = FromDto(dto);
                _byKey[definition.Key] = definition;
                _byEntry[definition.PrimaryEntry] = definition.Key;
                foreach (uint member in definition.MemberEntries ?? [])
                    _byEntry.TryAdd(member, definition.Key);
            }
            catch (Exception ex)
            {
                _errors.Add($"{Path.GetFileName(path)}: {ex.Message}");
            }
        }
        return _byKey.Count;
    }

    public void Save(EncounterDefinition definition, string? fileName = null)
    {
        System.IO.Directory.CreateDirectory(Directory);
        string path = Path.Combine(Directory, fileName ?? $"{definition.Key}.json");
        File.WriteAllText(path, JsonSerializer.Serialize(ToDto(definition), JsonOptions));
    }

    // ── DTO ⇄ model ──────────────────────────────────────────────────────────

    public static EncounterDefinition FromDto(EncounterFileDto dto)
    {
        EncounterCoverage coverage = EncounterCoverage.None;
        foreach (string flag in dto.Coverage ?? [])
            if (Enum.TryParse(flag, ignoreCase: true, out EncounterCoverage parsed)) coverage |= parsed;

        return new EncounterDefinition(
            Key: dto.Key,
            Name: dto.Name,
            PrimaryEntry: dto.PrimaryEntry,
            Phases: (dto.Phases ?? []).Select(FromDto).ToArray(),
            Abilities: (dto.Abilities ?? []).Select(FromDto).ToArray(),
            Provenance: new EncounterProvenance(
                dto.Provenance?.Source ?? "authored",
                dto.Provenance?.CoreBuildHash,
                dto.Provenance?.DbRevision,
                dto.Provenance?.ContentPatch,
                dto.Provenance?.CapturedUtc),
            Coverage: coverage,
            MemberEntries: dto.MemberEntries,
            MapIds: dto.MapIds,
            Actors: (dto.Actors ?? []).Select(FromDto).ToArray(),
            SchemaVersion: dto.SchemaVersion,
            Note: dto.Note);
    }

    private static EncounterActorSpec FromDto(ActorDto dto) => new(
        dto.Key, dto.Name, dto.Entry, dto.Role, dto.Position, dto.Facing,
        dto.BoundingRadius, dto.CombatReach, dto.Level, dto.MaxHealth,
        dto.DisplayId, dto.DisplayScale,
        dto.Moves?.Select(m => new TimedMove(m.TimeMs, m.Position, m.Anchor, m.PhaseKey,
            m.ArrivalFacing ?? float.NaN, m.Teleport)).ToArray(),
        dto.Dps, dto.Job,
        dto.IdleMovement is { } idle
            ? new IdleMovementSpec(idle.Kind, idle.WanderYards,
                idle.Points?.Select(p => new IdleWaypoint(p.Position, p.WaitMs)).ToArray(),
                idle.Note)
            : null,
        dto.RunSpeedYdPerSec, dto.WalkSpeedYdPerSec, dto.DetectionRangeYards,
        dto.PlayerRules is { } rules
            ? new EncounterPlayerRules(rules.AlwaysFaceBoss, CombatPlanFromDto(rules.Plan))
            : null);

    /// <summary>Single file-format mapping shared by authored encounter documents and
    /// the per-character combat-plan store.</summary>
    public static CombatPlan? CombatPlanFromDto(CombatPlanDto? dto) => dto is null ? null : new CombatPlan(
        dto.Name,
        dto.Movement is { } movement
            ? new CombatMovementPlan(movement.Mode, FromDto(movement.Anchor),
                movement.MinRangeYards, movement.MaxRangeYards,
                movement.FacePrimaryEnemy)
            : null,
        dto.Engagement,
        dto.SupportPriorities?.Select(priority => new CombatSupportPriority(
            FromDto(priority.Target) ?? CombatSubject.LowestHealth,
            priority.OnlyWhenBelowHealthPercent, priority.Enabled)).ToArray(),
        dto.EnemyPriorities?.Select(priority =>
            new CombatEnemyPriority(priority.Kind, priority.Enabled)).ToArray(),
        dto.Responsibilities?.ToArray(),
        dto.Resources is { } resources
            ? new CombatResourcePolicy(resources.ReservePercent,
                resources.EmergencyHealthPercent, resources.SaveMajorCooldowns)
            : null,
        dto.Fallback,
        dto.Rotation?.Select(intent =>
            new CombatAbilityIntent(intent.SpellId, intent.Name, intent.Enabled)).ToArray(),
        dto.ClassId);

    private static CombatSubject? FromDto(CombatSubjectDto? dto) => dto is null ? null :
        new CombatSubject(dto.Kind, dto.Role, Math.Max(dto.Ordinal, 1));

    private static EncounterPhase FromDto(PhaseDto dto) => new(
        dto.Key, dto.Name,
        (dto.Transitions ?? []).Select(FromDto).ToArray(),
        (dto.OnEnter ?? []).Select(FromDto).ToArray(),
        dto.CasterFlying, dto.MeleeEnabled, dto.Note);

    private static EncounterTransition FromDto(TransitionDto dto) => new(
        dto.ToPhase, FromDto(dto.Trigger), dto.Fidelity,
        (dto.Steps ?? []).Select(FromDto).ToArray(),
        (dto.Sources ?? []).Select(FromDto).ToArray(),
        dto.Note);

    private static EncounterAbility FromDto(AbilityDto dto) => new(
        dto.Key, dto.Name, dto.SpellId,
        FromDto(dto.Trigger), FromDto(dto.Timing), FromDto(dto.Target), FromDto(dto.Geometry),
        dto.Fidelity, dto.Phases, dto.ChancePercent, dto.CastTimeMs,
        (dto.Steps ?? []).Select(FromDto).ToArray(),
        (dto.Sources ?? []).Select(FromDto).ToArray(),
        dto.Note);

    private static EncounterStep FromDto(StepDto dto) => new(
        dto.Kind, dto.DurationMs, dto.Point, dto.SpellId, dto.Entry,
        dto.Count, dto.Value, dto.Flag, dto.PhaseKey, dto.Note, dto.DisplayId);

    private static EncounterSourceRef FromDto(SourceDto dto) => new(dto.Kind, dto.Location, dto.Detail);

    private static EncounterTriggerSpec FromDto(TriggerDto? dto) => dto is null
        ? EncounterTriggerSpec.Manual
        : new EncounterTriggerSpec(dto.Kind, dto.Threshold, dto.Param1, dto.Param2);

    private static EncounterTiming FromDto(TimingDto? dto) => dto is null
        ? EncounterTiming.Never
        : new EncounterTiming(dto.InitialMinMs, dto.InitialMaxMs, dto.RepeatMinMs, dto.RepeatMaxMs);

    private static EncounterTargetSpec FromDto(TargetDto? dto) => dto is null
        ? EncounterTargetSpec.Victim
        : new EncounterTargetSpec(dto.Kind, dto.Point, dto.Param1);

    private static EncounterGeometrySpec FromDto(GeometryDto? dto) => dto is null
        ? EncounterGeometrySpec.None
        : new EncounterGeometrySpec(dto.Kind, dto.Radius, dto.ConeDegrees, dto.Width,
            dto.ProjectileSpeed, dto.DurationMs, dto.Points, dto.PointSpellIds);

    public static EncounterFileDto ToDto(EncounterDefinition definition) => new()
    {
        SchemaVersion = definition.SchemaVersion,
        Key = definition.Key,
        Name = definition.Name,
        PrimaryEntry = definition.PrimaryEntry,
        MemberEntries = definition.MemberEntries?.ToList(),
        MapIds = definition.MapIds?.ToList(),
        Note = definition.Note,
        Coverage = definition.Coverage == EncounterCoverage.None
            ? null
            : definition.Coverage.ToString().Split(", ").ToList(),
        Provenance = new ProvenanceDto
        {
            Source = definition.Provenance.Source,
            CoreBuildHash = definition.Provenance.CoreBuildHash,
            DbRevision = definition.Provenance.DbRevision,
            ContentPatch = definition.Provenance.ContentPatch,
            CapturedUtc = definition.Provenance.CapturedUtc,
        },
        Actors = definition.Actors?.Select(a => new ActorDto
        {
            Key = a.Key, Name = a.Name, Entry = a.Entry, Role = a.Role,
            Position = a.Position, Facing = a.Facing, BoundingRadius = a.BoundingRadius,
            CombatReach = a.CombatReach, Level = a.Level, MaxHealth = a.MaxHealth,
            DisplayId = a.DisplayId, DisplayScale = a.DisplayScale,
            Moves = a.Moves?.Select(m => new MoveDto
            {
                TimeMs = m.TimeMs, Position = m.Position, Anchor = m.Anchor,
                PhaseKey = m.PhaseKey,
                ArrivalFacing = m.HasArrivalFacing ? m.ArrivalFacing : null,
                Teleport = m.Teleport,
            }).ToList(),
            Dps = a.Dps,
            Job = a.Job,
            IdleMovement = a.IdleMovement is { } idle
                ? new IdleMovementDto
                {
                    Kind = idle.Kind, WanderYards = idle.WanderYards, Note = idle.Note,
                    Points = idle.Points?.Select(p => new IdleWaypointDto
                    { Position = p.Position, WaitMs = p.WaitMs }).ToList(),
                }
                : null,
            RunSpeedYdPerSec = a.RunSpeedYdPerSec,
            WalkSpeedYdPerSec = a.WalkSpeedYdPerSec,
            DetectionRangeYards = a.DetectionRangeYards,
            PlayerRules = a.PlayerRules is { } rules
                ? new PlayerRulesDto
                {
                    AlwaysFaceBoss = rules.AlwaysFaceBoss,
                    Plan = CombatPlanToDto(rules.Plan),
                }
                : null,
        }).ToList(),
        Phases = definition.Phases.Select(p => new PhaseDto
        {
            Key = p.Key, Name = p.Name, CasterFlying = p.CasterFlying,
            MeleeEnabled = p.MeleeEnabled, Note = p.Note,
            OnEnter = p.OnEnter?.Select(ToDto).ToList(),
            Transitions = p.Transitions?.Select(t => new TransitionDto
            {
                ToPhase = t.ToPhase, Fidelity = t.Fidelity, Note = t.Note,
                Trigger = ToDto(t.Trigger),
                Steps = t.Steps?.Select(ToDto).ToList(),
                Sources = t.Sources?.Select(ToDto).ToList(),
            }).ToList(),
        }).ToList(),
        Abilities = definition.Abilities.Select(a => new AbilityDto
        {
            Key = a.Key, Name = a.Name, SpellId = a.SpellId, Fidelity = a.Fidelity,
            Phases = a.Phases?.ToList(), ChancePercent = a.ChancePercent,
            CastTimeMs = a.CastTimeMs, Note = a.Note,
            Trigger = ToDto(a.Trigger), Timing = ToDto(a.Timing),
            Target = ToDto(a.Target), Geometry = ToDto(a.Geometry),
            Steps = a.Steps?.Select(ToDto).ToList(),
            Sources = a.Sources?.Select(ToDto).ToList(),
        }).ToList(),
    };

    /// <summary>Single model-to-file mapping shared by authored encounter documents and
    /// the per-character combat-plan store.</summary>
    public static CombatPlanDto? CombatPlanToDto(CombatPlan? plan) => plan is null ? null : new CombatPlanDto
    {
        Name = plan.Name,
        Movement = plan.Movement is { } movement
            ? new CombatMovementDto
            {
                Mode = movement.Mode,
                Anchor = ToDto(movement.Anchor),
                MinRangeYards = movement.MinRangeYards,
                MaxRangeYards = movement.MaxRangeYards,
                FacePrimaryEnemy = movement.FacePrimaryEnemy,
            }
            : null,
        Engagement = plan.Engagement,
        SupportPriorities = plan.SupportPriorities?.Select(priority =>
            new CombatSupportPriorityDto
            {
                Target = ToDto(priority.Target) ?? new CombatSubjectDto(),
                OnlyWhenBelowHealthPercent = priority.OnlyWhenBelowHealthPercent,
                Enabled = priority.Enabled,
            }).ToList(),
        EnemyPriorities = plan.EnemyPriorities?.Select(priority =>
            new CombatEnemyPriorityDto
            {
                Kind = priority.Kind,
                Enabled = priority.Enabled,
            }).ToList(),
        Responsibilities = plan.Responsibilities?.ToList(),
        Resources = plan.Resources is { } resources
            ? new CombatResourcePolicyDto
            {
                ReservePercent = resources.ReservePercent,
                EmergencyHealthPercent = resources.EmergencyHealthPercent,
                SaveMajorCooldowns = resources.SaveMajorCooldowns,
            }
            : null,
        Fallback = plan.Fallback,
        Rotation = plan.Rotation?.Select(intent => new CombatAbilityIntentDto
        {
            SpellId = intent.SpellId,
            Name = intent.Name,
            Enabled = intent.Enabled,
        }).ToList(),
        ClassId = plan.ClassId,
    };

    private static CombatSubjectDto? ToDto(CombatSubject? subject) => subject is null ? null :
        new CombatSubjectDto
        {
            Kind = subject.Kind,
            Role = subject.Role,
            Ordinal = subject.Ordinal,
        };

    private static StepDto ToDto(EncounterStep s) => new()
    {
        Kind = s.Kind, DurationMs = s.DurationMs, Point = s.Point, SpellId = s.SpellId,
        Entry = s.Entry, Count = s.Count, Value = s.Value, Flag = s.Flag,
        PhaseKey = s.PhaseKey, Note = s.Note, DisplayId = s.DisplayId,
    };

    private static SourceDto ToDto(EncounterSourceRef s) =>
        new() { Kind = s.Kind, Location = s.Location, Detail = s.Detail };

    private static TriggerDto ToDto(EncounterTriggerSpec t) =>
        new() { Kind = t.Kind, Threshold = t.Threshold, Param1 = t.Param1, Param2 = t.Param2 };

    private static TimingDto ToDto(EncounterTiming t) => new()
    {
        InitialMinMs = t.InitialMinMs, InitialMaxMs = t.InitialMaxMs,
        RepeatMinMs = t.RepeatMinMs, RepeatMaxMs = t.RepeatMaxMs,
    };

    private static TargetDto ToDto(EncounterTargetSpec t) =>
        new() { Kind = t.Kind, Point = t.Point, Param1 = t.Param1 };

    private static GeometryDto ToDto(EncounterGeometrySpec g) => new()
    {
        Kind = g.Kind, Radius = g.Radius, ConeDegrees = g.ConeDegrees, Width = g.Width,
        ProjectileSpeed = g.ProjectileSpeed, DurationMs = g.DurationMs,
        Points = g.Points?.ToList(), PointSpellIds = g.PointSpellIds?.ToList(),
    };
}
